"""Public BYOK settings API."""

from .credential_store import (
    DEFAULT_KEYRING_ACCOUNT,
    DEFAULT_KEYRING_SERVICE,
    CredentialBackend,
    CredentialStore,
    CredentialStoreUnavailable,
    KeyringCredentialStore,
    MemoryCredentialStore,
    SessionCredentialStore,
)
from .connection import (
    ConnectionCheck,
    ConnectionTestResult,
    ProviderConnectionTester,
)
from .models import (
    APISettings,
    DEFAULT_FAST_MODEL,
    DEFAULT_FAST_TIMEOUT,
    DEFAULT_IMAGE_MODEL,
    DEFAULT_IMAGE_TIMEOUT,
    DEFAULT_MAIN_MODEL,
    DEFAULT_MAIN_TIMEOUT,
    TEAMO_BASE_URL,
    TEAMO_PRESET,
    ApiSettings,
    ApiSettingsSnapshot,
    CredentialStatus,
    ProviderPreset,
    ProviderSettingsProfile,
    RuntimeProviderConfig,
)
from .repository import (
    APISettingsRepository,
    JsonSettingsRepository,
    SettingsRepository,
    SettingsRepositoryError,
    default_settings_path,
)
from .service import (
    APISettingsService,
    ApiSettingsService,
    CredentialNotConfiguredError,
    UnsupportedProviderPreset,
)

__all__ = [
    "APISettings",
    "APISettingsRepository",
    "APISettingsService",
    "ApiSettings",
    "ApiSettingsService",
    "ApiSettingsSnapshot",
    "CredentialBackend",
    "ConnectionCheck",
    "ConnectionTestResult",
    "CredentialNotConfiguredError",
    "CredentialStatus",
    "CredentialStore",
    "CredentialStoreUnavailable",
    "DEFAULT_FAST_MODEL",
    "DEFAULT_FAST_TIMEOUT",
    "DEFAULT_IMAGE_MODEL",
    "DEFAULT_IMAGE_TIMEOUT",
    "DEFAULT_KEYRING_ACCOUNT",
    "DEFAULT_KEYRING_SERVICE",
    "DEFAULT_MAIN_MODEL",
    "DEFAULT_MAIN_TIMEOUT",
    "JsonSettingsRepository",
    "KeyringCredentialStore",
    "MemoryCredentialStore",
    "ProviderPreset",
    "ProviderConnectionTester",
    "ProviderSettingsProfile",
    "RuntimeProviderConfig",
    "SessionCredentialStore",
    "SettingsRepository",
    "SettingsRepositoryError",
    "TEAMO_BASE_URL",
    "TEAMO_PRESET",
    "UnsupportedProviderPreset",
    "default_settings_path",
]
