"""Build the standalone, visual-only frontend preview.

The Streamlit Components v2 fragment and stylesheet remain the canonical UI
sources.  This utility only wraps those sources in a complete HTML document so
the layout can be reviewed directly from ``file://`` without running a server.
"""

from __future__ import annotations

import argparse
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
FRONTEND_DIR = PROJECT_ROOT / "app" / "ui" / "frontend"
COMPONENT_HTML = FRONTEND_DIR / "component.html"
COMPONENT_CSS = FRONTEND_DIR / "component.css"
DEFAULT_OUTPUT = FRONTEND_DIR / "preview.html"


def render_preview() -> str:
    """Return a deterministic standalone document from the canonical sources."""

    fragment = COMPONENT_HTML.read_text(encoding="utf-8").rstrip()
    stylesheet = COMPONENT_CSS.read_text(encoding="utf-8").rstrip()

    if "</style" in stylesheet.lower():
        raise ValueError("component.css cannot contain a closing style tag")

    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Following blowing · Frontend Preview</title>
  <meta name="description" content="Following blowing static frontend visual preview">
  <!-- Generated by scripts/build_frontend_preview.py. Do not edit directly. -->
  <style data-source="component.css">
{stylesheet}
  </style>
</head>
<body data-preview-mode="static" style="margin:0;min-height:100%;background:#f5f6fb">
  <aside id="previewDevelopmentNotice" role="note" style="width:min(1220px,92vw);margin:16px auto 0;padding:12px 16px;box-sizing:border-box;border:1px solid #bfdbfe;border-radius:12px;background:#eff6ff;color:#1e3a8a;font-family:'Microsoft YaHei',Arial,sans-serif;line-height:1.55;box-shadow:0 5px 16px rgba(15,23,42,.06)">
    <strong>Following blowing · Static UI Preview</strong><br>
    This file is for visual preview only.<br>
    Live Agent interaction requires Streamlit.<br>
    Static UI Preview — image upload is not connected to the backend. Use <code>http://localhost:8501</code> for live upload.
  </aside>
{fragment}
</body>
</html>
"""


def build_preview(output_path: Path = DEFAULT_OUTPUT) -> Path:
    """Write the preview document and return its resolved output path."""

    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_preview(), encoding="utf-8")
    return output_path


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build the Following blowing static frontend preview."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output HTML path (default: app/ui/frontend/preview.html)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when the existing output is missing or stale.",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    expected = render_preview()
    output_path = args.output.resolve()

    if args.check:
        if not output_path.is_file():
            print(f"Static preview is missing: {output_path}")
            return 1
        if output_path.read_text(encoding="utf-8") != expected:
            print(f"Static preview is stale: {output_path}")
            return 1
        print(f"Static preview is current: {output_path}")
        return 0

    built = build_preview(output_path)
    print(f"Static preview built: {built}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
