[server]
headless = true
maxUploadSize = 20

[browser]
gatherUsageStats = false

[theme]
base = "light"
backgroundColor = "#f5f6fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#202124"
primaryColor = "#111827"
font = "sans-serif"

